- README.md
- index.html
added the user story , html , & css
> initial upload

- Assets/style.css
- index.html
- psuedocode.md
added nav, footer, boxes into main. Want to get layout set up and start creating tags.
> mt-added framework to html. fixed 06

- index.html
- psuedocode.md
- scripts/api/hotelApi.js
- scripts/api/weatherApi.js
- scripts/api/zomatoApi.js
- scripts/main.js
- Added in a scripted folder to put in all the javascript files in.. Also added a api folder to house each API to organize our code more.
- My next plan is to actually start the logic portion of the javascript in main.js and try to grab the data and display it.
> FIxed Issue #9 

- index.html
- psuedocode.md
- scripts/api/weatherApi.js
- scripts/main.js
Added my pseudo code portion for the main javascript file to stay completely focused on all of my javascript files
> Fixed issue #04

- index.html
- scripts/api/hotelApi.js
- scripts/api/weatherApi.js
- scripts/api/zomatoApi.js
- scripts/main.js
Fixed the issue of not having any logic put into the website, for this merge it will add more Javascript to work with getting the cityname from the search bar as well as have the moment.js in html and have some variables ready for use when we are more further into production.
> Fixed Issue 08

- Assets/aboutus.html
- Assets/contactus.html
- Assets/style.css
- index.html
added some radio buttons and the contact & about us file
> added radio buttons & 2 html files

- index.html
- scripts/api/weatherApi.js
- scripts/main.js
Fixed the issue of logical pathways for when the user types the city name and presses enter, it will call the weather API and do the forecast section, then it will display them and check to see if the hotel and restaurant is true or false and call those APIs if they are true and not call them if they are false.
> Fixed Issue #16

- index.html
- scripts/api/hotelApi.js
- scripts/api/weatherApi.js
Grabbed the hotel API info which is just the info for the hotel name right now and displaying it onto one of the cards. It gets 3 suggested hotels given to me and then displays them in the card and you can select which one you want.
> Fixed Issue #20

- index.html
added 5 day forecast and named elements. need to fix placement and other css
> added 5day Forecast

- Assets/style.css
- index.html
- scripts/api/hotelApi.js
- scripts/api/weatherApi.js
- scripts/api/zomatoApi.js
- scripts/main.js
Grabbed and display 9 restaurants in the city the the user types. Also hid the cards in CSS until the user presses enter on the city to make it less crowded and more minimalistic. Going to fix to add info into the 5 day forecast now.
> Ch 21 zomato api

- Assets/style.css
- index.html
- scripts/api/weatherApi.js
- scripts/main.js
Added 5 day forecast to the web app, as well as did slight CSS to the logo on top to give it a better immersion and make it seem a lot more cooler that is it popped off the nav. Looks way cooler now. Going to work on Javascript and more CSS and HTML to help push things along as well.
> Ch 19 5 day weather api

- Assets/style.css
- index.html
- scripts/main.js
Adding in some changes to the web app
> Pushing changes for everyone else

- Assets/style.css
- index.html
added select drop down buttons to nav. Cristian is currently working on functionality
> added select buttons to nav

- Assets/contactus.html
- Assets/styleaboutus.css
- Assets/stylecontactus.css
> added more styling

- Assets/style.css
- index.html
- scripts/main.js
Added the filter functionality, need to fix the look of it and grab the values of it as well as figure out why the city name is not getting grabbed anymore
> Ch 18 select buttons js

- Assets/aboutus.html
- Assets/style.css
added cards took off search for about me main layout
> Mt 14 aboutmelayout

- index.html
- scripts/main.js
Fixed the search from not grabbing data, started trying to get data from the options to see if the user selected a specific option or all
> fixed issue with city name not being grabbed

- Assets/aboutus.html
- Assets/contactus.html
- index.html
linked the HTML files to the Nav bar icons (including logo) on the index, about us, & contact us page
> linked html files

- Assets/style.css
- index.html
- scripts/api/hotelApi.js
- scripts/main.js
Got to grab the users selections for the other options and displays accordingly!
> Ch 18 grab selection

- Assets/contactus.html
- Assets/stylecontactus.css
added contact me form onto page , button , and fixed message box in css
> added contact me form

- Assets/style.css
- index.html
- scripts/api/weatherApi.js
Fixed Issue #25 as well as added a few more css coloring to the background of the 5-day and hid the cars to give it more open space in the beginning. Will work on moving the cards better soon after my Javascript portions.
> Ch 25 5day bg and more

- Assets/style.css
- Assets/styleaboutus.css
- index.html
Added a open look to the opening page of the HTML and gave it a few css changes.
> Fixed Issue #12

- index.html
- scripts/localStorage.js
Added the html changes that joe had plus some of my own
> fixed side issues

- Assets/contactus.html
- scripts/localStorage.js
Added functionality to the submit button to grab the information and put it into local storage since we do not have a database to store that info yet. But also cleared the screen once the user has submittted something in
> Ch 30 submit btn ls

- Assets/contactus.html
- Assets/style.css
- index.html
- scripts/api/weatherApi.js
- scripts/localStorage.js
Changed the css and some id names for the index html. Gave the weather cards a more sleek look and added upon what Joe did. Weather cards and basically all of the home page is done!
> Fixed Issue #27

- Assets/aboutus.html
Added info in the about us page
> Ch nth aboutus

- Assets/aboutus.html
- Assets/contactus.html
- Assets/style.css
- index.html
added fonts and styling to our main page.
> added styling to main page

- Assets/style.css
Added last minute touches to the main page
> Added some touches to the main page of the web app
